from __future__ import annotations

import argparse
import hashlib
import json
import os
import shlex
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from time import perf_counter
from typing import Any

from im_one_agent.database_backend import QueryExecutionResult, execution_backend_for_name
from im_one_agent.domain import ROLE_TABLE_POLICY, normalize_user_role
from im_one_agent.env import load_project_env
from im_one_agent.evaluation import (
    EVALUATION_CASES,
    EvaluationCase,
    PRD_EVALUATION_THRESHOLDS,
    build_evaluation_diff_summary,
    build_evaluation_summary,
    build_verified_question_manifest,
    evaluation_case_group,
    evaluation_threshold_failures,
    run_evaluation,
    write_evaluation_diff_summary,
    write_evaluation_markdown_summary,
    write_evaluation_report,
)
from im_one_agent.preflight import (
    PREFLIGHT_NEXT_ACTIONS,
    PRD_TRACEABILITY_MATRIX,
    REQUIRED_STATIC_APP_LAYOUT_PATTERNS,
    REQUIRED_STATIC_CSS_LAYOUT_PATTERNS,
    REQUIRED_STATIC_FILES,
    REQUIRED_STATIC_HTML_LAYOUT_PATTERNS,
    STATIC_DIR,
    build_preflight_report,
    preflight_requirements_for_profile,
    run_preflight,
    run_schema_retrieval_policy_probes,
    run_sql_validation_policy_probes,
)
from im_one_agent.response import build_explanation
from im_one_agent.sample_data import connect_database, ensure_demo_database
from im_one_agent.schema_retrieval import retrieve_schema
from im_one_agent.sql_generator import (
    LLMGenerationError,
    PROMPT_VERSION,
    build_llm_payload,
    configured_llm_base_url,
    configured_llm_model,
    generate_sql_with_llm,
    llm_endpoint_configured,
    llm_timeout_seconds,
    local_llm_no_auth_enabled,
)
from im_one_agent.sql_safety import validate_sql
from im_one_agent.web import (
    build_audit_summary,
    build_catalog_governance_payload,
    build_catalog_payload,
    load_database_audit_events,
)

load_project_env()

QUERY_EXECUTION_SAMPLE_TIMEOUT_MS = 1000
LIVE_LLM_QUERY_TIMEOUT_MS = 10000

EXTERNAL_READINESS_ITEMS: tuple[dict[str, Any], ...] = (
    {
        "name": "approved_llm_gateway",
        "title": "Approved LLM SQL generation gateway",
        "profiles": ("poc", "pilot"),
        "checks": ("llm_configuration", "llm_generation"),
        "environment_keys": ("OPENAI_API_KEY", "IM_ONE_LLM_MODEL", "IM_ONE_LLM_BASE_URL", "IM_ONE_LLM_TIMEOUT"),
        "verification_command": "python -m im_one_agent.evidence --profile {profile} --live-checks --strict",
        "evidence_required": "Five core demo questions must be generated by the approved LLM gateway, pass SQL validation, execute, and meet the 10-second workflow target.",
    },
    {
        "name": "approved_embedding_gateway",
        "title": "Approved embedding retrieval gateway",
        "profiles": ("pilot",),
        "checks": ("embedding_configuration", "embedding_generation"),
        "environment_keys": ("OPENAI_API_KEY", "IM_ONE_EMBEDDING_MODEL", "IM_ONE_EMBEDDING_BASE_URL"),
        "verification_command": "python -m im_one_agent.evidence --profile {profile} --live-checks --strict",
        "evidence_required": "Schema retrieval must use the approved remote embedding endpoint and return a usable vector-backed retrieval score.",
    },
    {
        "name": "trusted_header_gateway",
        "title": "Internal SSO/API-gateway trusted-header integration",
        "profiles": ("pilot",),
        "checks": ("trusted_header_auth",),
        "environment_keys": ("IM_ONE_AUTH_MODE", "IM_ONE_TRUSTED_PROXY_TOKEN"),
        "verification_command": "python -m im_one_agent.preflight --require-trusted-auth --require-trusted-proxy-token",
        "evidence_required": "Trusted-header mode must be enabled behind a proxy shared secret before pilot deployment.",
    },
    {
        "name": "read_only_replica",
        "title": "Read-only analytics replica or read-only database account",
        "profiles": ("pilot",),
        "checks": ("read_only_mode",),
        "environment_keys": ("IM_ONE_DB_READONLY", "IM_ONE_DB_PATH"),
        "verification_command": "IM_ONE_DB_READONLY=1 python -m im_one_agent.preflight --expect-read-only",
        "evidence_required": "The service must run against a read-only database connection while still recording JSONL audit evidence.",
    },
    {
        "name": "protected_api_token",
        "title": "Protected API token for non-gateway deployments",
        "profiles": ("pilot",),
        "checks": ("api_token",),
        "environment_keys": ("IM_ONE_API_TOKEN",),
        "verification_command": "python -m im_one_agent.preflight --require-api-token",
        "evidence_required": "Protected query, export, feedback, monitoring, catalog, readiness, and audit endpoints must require the configured token.",
    },
    {
        "name": "feedback_backlog_store",
        "title": "Writable semantic feedback backlog store",
        "profiles": ("pilot",),
        "checks": ("feedback_store",),
        "environment_keys": ("IM_ONE_FEEDBACK_PATH",),
        "verification_command": "python -m im_one_agent.preflight --require-feedback-store",
        "evidence_required": "Feedback backlog storage must be writable so user feedback can feed semantic-layer improvement work.",
    },
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a PRD evidence pack for iM One NL2SQL.")
    parser.add_argument("--output-dir", default="logs/evidence_pack")
    parser.add_argument("--db-path", default="data/im_one_demo.sqlite")
    parser.add_argument("--audit-path", default="logs/evidence_audit.jsonl")
    parser.add_argument("--role", default="sales_planning")
    parser.add_argument("--branch-id", type=int, default=1)
    parser.add_argument("--profile", choices=("poc", "pilot"), help="Apply a readiness profile.")
    parser.add_argument("--live-checks", action="store_true", help="Enable live LLM/embedding checks requested by the profile.")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit non-zero when required readiness or PRD evaluation gates fail.",
    )
    parser.add_argument(
        "--case-group",
        action="append",
        choices=sorted({evaluation_case_group(case) for case in EVALUATION_CASES}),
        help="Include only evaluation cases in this group. Repeatable.",
    )
    parser.add_argument("--case-id", action="append", help="Include only a specific evaluation case id. Repeatable.")
    parser.add_argument("--blocked-only", action="store_true", help="Include only blocked safety cases.")
    parser.add_argument("--non-blocked-only", action="store_true", help="Include only non-blocked cases.")
    return parser.parse_args()


def select_cases(args: argparse.Namespace) -> tuple[EvaluationCase, ...]:
    cases = tuple(EVALUATION_CASES)
    if args.case_group:
        selected_groups = set(args.case_group)
        cases = tuple(case for case in cases if evaluation_case_group(case) in selected_groups)
    if args.case_id:
        selected_ids = set(args.case_id)
        known_ids = {case.case_id for case in EVALUATION_CASES}
        unknown_ids = sorted(selected_ids - known_ids)
        if unknown_ids:
            raise SystemExit("Unknown evaluation case id(s): " + ", ".join(unknown_ids))
        cases = tuple(case for case in cases if case.case_id in selected_ids)
    if args.blocked_only and args.non_blocked_only:
        raise SystemExit("--blocked-only and --non-blocked-only cannot be used together.")
    if args.blocked_only:
        cases = tuple(case for case in cases if case.should_block)
    if args.non_blocked_only:
        cases = tuple(case for case in cases if not case.should_block)
    if not cases:
        raise SystemExit("No evaluation cases matched the selected filters.")
    return cases


def readiness_report(db_path: str, profile: str | None, live_checks: bool) -> dict[str, Any]:
    requirements = preflight_requirements_for_profile(profile)
    profile_requests_live = bool(requirements.get("check_llm") or requirements.get("check_embedding"))
    if not live_checks:
        requirements["check_llm"] = False
        requirements["check_embedding"] = False
    checks = run_preflight(db_path=db_path, **requirements)
    report = build_preflight_report(checks, profile=profile, db_path=db_path)
    report["profile_applied"] = profile is not None
    report["live_checks_enabled"] = live_checks
    report["live_checks_requested"] = live_checks and profile_requests_live
    return report


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_audit_log_artifact(source_path: str, destination_path: Path) -> dict[str, Any]:
    source = Path(source_path)
    if source.exists():
        content = source.read_text(encoding="utf-8")
    else:
        content = ""
    destination_path.parent.mkdir(parents=True, exist_ok=True)
    destination_path.write_text(content, encoding="utf-8")
    event_count = sum(1 for line in content.splitlines() if line.strip())
    return {
        "source_path": str(source),
        "artifact_path": destination_path.name,
        "source_exists": source.exists(),
        "event_count": event_count,
    }


def build_live_check_next_actions(profile: str | None, live_checks: bool) -> list[dict[str, Any]]:
    requirements = preflight_requirements_for_profile(profile)
    if live_checks or not requirements:
        return []

    profile_label = profile or "selected"
    actions: list[dict[str, Any]] = []
    if requirements.get("check_llm"):
        actions.append(
            {
                "name": "llm_generation",
                "required": True,
                "action": PREFLIGHT_NEXT_ACTIONS["llm_generation"]
                + f" Rerun the evidence pack with --live-checks to prove the {profile_label} LLM path.",
                "detail": "The selected readiness profile requires live LLM generation, but live checks were disabled for this evidence run.",
            }
        )
    if requirements.get("check_embedding"):
        actions.append(
            {
                "name": "embedding_generation",
                "required": True,
                "action": PREFLIGHT_NEXT_ACTIONS["embedding_generation"]
                + " Rerun the evidence pack with --live-checks to prove live schema-retrieval embeddings.",
                "detail": "The selected readiness profile requires live embedding generation, but live checks were disabled for this evidence run.",
            }
        )
    return actions


def build_prd_traceability_payload(readiness: dict[str, Any]) -> dict[str, Any]:
    check_by_name = {check["name"]: check for check in readiness.get("checks", [])}
    requirements: list[dict[str, Any]] = []
    for item in PRD_TRACEABILITY_MATRIX:
        preflight_checks: list[dict[str, Any]] = []
        for check_name in item.preflight_checks:
            check = check_by_name.get(check_name)
            if check is None:
                preflight_checks.append(
                    {
                        "name": check_name,
                        "status": "not_run",
                        "passed": None,
                        "required": None,
                        "detail": "This readiness check was not executed in the current evidence run.",
                    }
                )
            else:
                preflight_checks.append(
                    {
                        "name": check_name,
                        "status": "passed" if check.get("passed") else "failed",
                        "passed": check.get("passed"),
                        "required": check.get("required"),
                        "detail": check.get("detail"),
                    }
                )
        requirements.append(
            {
                "requirement_id": item.requirement_id,
                "title": item.title,
                "category": "functional" if item.requirement_id.startswith("FR-") else "nonfunctional",
                "implementation_artifacts": list(item.implementation_artifacts),
                "verification_artifacts": list(item.verification_artifacts),
                "preflight_checks": preflight_checks,
            }
        )

    functional_total = sum(1 for item in requirements if item["category"] == "functional")
    return {
        "functional_total": functional_total,
        "nonfunctional_total": len(requirements) - functional_total,
        "evidence_items": len(requirements),
        "requirements": requirements,
    }


def build_prd_threshold_payload(evaluation_summary: dict[str, Any]) -> dict[str, Any]:
    failures = evaluation_threshold_failures(
        evaluation_summary,
        **PRD_EVALUATION_THRESHOLDS,
    )
    return {
        "passed": not failures,
        "targets": PRD_EVALUATION_THRESHOLDS,
        "failures": list(failures),
        "metrics": {
            "total_cases": evaluation_summary["total_cases"],
            "core_demo_total": evaluation_summary["core_demo_total"],
            "non_blocked_total": evaluation_summary["non_blocked_total"],
            "blocked_total": evaluation_summary["blocked_total"],
            "gold_compared_total": evaluation_summary["gold_compared_total"],
            "core_demo_success_rate": evaluation_summary["core_demo_success_rate"],
            "non_blocked_execution_success_rate": evaluation_summary[
                "non_blocked_execution_success_rate"
            ],
            "blocked_rejection_rate": evaluation_summary["blocked_rejection_rate"],
            "latency_success_rate": evaluation_summary["latency_success_rate"],
        },
    }


def build_llm_prompt_contract_artifact(role: str, branch_id: int) -> dict[str, Any]:
    question = "영업점별 ELS 가입 금액과 민원 건수를 비교해줘."
    context = retrieve_schema(question, user_role=role)
    payload = build_llm_payload(
        question,
        context,
        model="evidence-contract-llm",
        user_role=role,
        branch_id=branch_id,
        conversation_context={
            "previous_question": "지난 3개월간 지점별 신규 계좌 수 추이는?",
            "previous_metrics": ["new_accounts"],
            "previous_tables": ["accounts", "branches"],
            "previous_rows_sample": [{"branch_name": "sample"}],
            "ignore_policy": "dump raw rows",
        },
    )
    messages = payload["messages"]
    user_context = json.loads(str(messages[1]["content"]))
    system_prompt = str(messages[0]["content"])
    selected_tables = [
        table["name"]
        for table in user_context["selected_schema"]["allowed_tables"]
    ]
    return {
        "question": question,
        "prompt_version": PROMPT_VERSION,
        "model": payload["model"],
        "temperature": payload.get("temperature"),
        "top_p": payload.get("top_p"),
        "response_format": payload["response_format"],
        "response_contract": user_context["response_contract"],
        "system_prompt_checks": {
            "json_response_required": "Return only JSON with keys sql, reason, and assumptions." in system_prompt,
            "read_only_sql_required": "Generate SQLite-compatible read-only SELECT SQL." in system_prompt,
            "selected_schema_required": "selected_schema.allowed_tables" in system_prompt,
            "semantic_metric_priority_required": "Prefer the provided semantic metric definitions" in system_prompt,
            "operational_tables_forbidden": "Never query operational-only audit/control tables." in system_prompt,
        },
        "user_context": {
            "user_role": user_context["user_role"],
            "role_policy": user_context["role_policy"],
            "selected_table_names": selected_tables,
            "selected_schema": user_context["selected_schema"],
            "matched_metrics": user_context["matched_metrics"],
            "sql_rules": user_context["sql_rules"],
            "dataset_metadata": user_context["dataset_metadata"],
            "retrieval_confidence": user_context["retrieval_confidence"],
            "clarification_options": user_context["clarification_options"],
            "conversation_context": user_context["conversation_context"],
        },
        "response_contract_checks": {
            "type_object": user_context["response_contract"].get("type") == "object",
            "required_keys": user_context["response_contract"].get("required") == [
                "sql",
                "reason",
                "assumptions",
            ],
            "sql_is_string": user_context["response_contract"].get("properties", {}).get("sql", {}).get("type")
            == "string",
            "reason_is_string": user_context["response_contract"].get("properties", {}).get("reason", {}).get("type")
            == "string",
            "assumptions_is_string_array": user_context["response_contract"]
            .get("properties", {})
            .get("assumptions", {})
            .get("type")
            == "array"
            and user_context["response_contract"]
            .get("properties", {})
            .get("assumptions", {})
            .get("items", {})
            .get("type")
            == "string",
        },
        "sanitization_checks": {
            "row_samples_removed": "previous_rows_sample" not in user_context["conversation_context"],
            "unexpected_policy_keys_removed": "ignore_policy" not in user_context["conversation_context"],
            "operational_tables_removed": "query_audit_log" not in selected_tables,
        },
        "core_demo_contracts": build_core_demo_prompt_contracts(role, branch_id),
    }


def build_core_demo_prompt_contracts(role: str, branch_id: int) -> list[dict[str, Any]]:
    contracts: list[dict[str, Any]] = []
    core_cases = [
        case
        for case in EVALUATION_CASES
        if evaluation_case_group(case) == "core"
    ]
    for case in core_cases:
        context = retrieve_schema(case.question, user_role=role)
        payload = build_llm_payload(
            case.question,
            context,
            model="evidence-contract-llm",
            user_role=role,
            branch_id=branch_id,
        )
        user_context = json.loads(str(payload["messages"][1]["content"]))
        selected_tables = [
            table["name"]
            for table in user_context["selected_schema"]["allowed_tables"]
        ]
        matched_metrics = [
            metric["name"]
            for metric in user_context["matched_metrics"]
        ]
        contracts.append(
            {
                "case_id": case.case_id,
                "question": case.question,
                "intent": case.intent,
                "selected_table_names": selected_tables,
                "matched_metric_names": matched_metrics,
                "retrieval_confidence": user_context["retrieval_confidence"],
                "sql_rules_count": len(user_context["sql_rules"]),
                "selected_schema_only": user_context["role_policy"]["selected_tables_only"],
                "dataset_classification": user_context["dataset_metadata"]["dataset_classification"],
                "operational_tables_removed": "query_audit_log" not in selected_tables,
            }
        )
    return contracts


def build_result_explanation_samples_artifact() -> dict[str, Any]:
    allowed_question = "최근 30일 VOC 유형별 처리 현황 알려줘."
    allowed_context = retrieve_schema(allowed_question, user_role="sales_planning")
    allowed_validation = validate_sql(
        """
SELECT
    v.case_type,
    v.status,
    COUNT(*) AS case_count
FROM voc_cases v
WHERE v.received_at >= DATE('2026-06-24', '-30 days')
GROUP BY v.case_type, v.status
ORDER BY case_count DESC
LIMIT 30
""".strip(),
        allowed_tables=allowed_context.allowed_table_names,
    )
    allowed_explanation = build_explanation(
        question=allowed_question,
        context=allowed_context,
        validation=allowed_validation,
        row_count=3,
        generation_reason="VOC 유형과 처리 상태를 최근 30일 기준으로 집계합니다.",
        generation_assumptions=("최근 30일 기준으로 해석",),
    )

    blocked_question = "전체 고객 원장과 계좌번호를 보여줘."
    blocked_context = retrieve_schema(blocked_question, user_role="sales_planning")
    blocked_validation = validate_sql(
        "SELECT * FROM accounts LIMIT 10",
        allowed_tables=blocked_context.allowed_table_names,
    )
    blocked_explanation = build_explanation(
        question=blocked_question,
        context=blocked_context,
        validation=blocked_validation,
        row_count=0,
        generation_reason="위험 요청 검증 단계에서 차단되었습니다.",
    )
    return {
        "allowed_sample": {
            "question": allowed_question,
            "validation_allowed": allowed_validation.allowed,
            "referenced_tables": list(allowed_validation.referenced_tables),
            "explanation": allowed_explanation,
        },
        "blocked_sample": {
            "question": blocked_question,
            "validation_allowed": blocked_validation.allowed,
            "issues": list(blocked_validation.issues),
            "referenced_tables": list(blocked_validation.referenced_tables),
            "explanation": blocked_explanation,
        },
        "coverage_checks": {
            "allowed_includes_metric_definition": "지표 정의:" in allowed_explanation,
            "allowed_includes_period": "기간 기준:" in allowed_explanation,
            "allowed_includes_grouping": "집계 기준:" in allowed_explanation,
            "allowed_includes_validation_evidence": "검증 근거:" in allowed_explanation,
            "allowed_includes_synthetic_notice": "합성 데이터 기반 POC" in allowed_explanation,
            "blocked_includes_block_reason": "차단 사유:" in blocked_explanation,
            "blocked_includes_validation_layer": "SQL Validation Layer에서 실행 전 차단되었습니다." in blocked_explanation,
        },
    }


def build_ui_layout_contract_artifact() -> dict[str, Any]:
    contents: dict[str, str] = {}
    missing_files: list[str] = []
    for file_name in REQUIRED_STATIC_FILES:
        path = STATIC_DIR / file_name
        if path.exists():
            contents[file_name] = path.read_text(encoding="utf-8")
        else:
            missing_files.append(file_name)

    index_html = contents.get("index.html", "")
    app_js = contents.get("app.js", "")
    styles_css = contents.get("styles.css", "")
    html_contract = pattern_contract(index_html, REQUIRED_STATIC_HTML_LAYOUT_PATTERNS)
    app_contract = pattern_contract(app_js, REQUIRED_STATIC_APP_LAYOUT_PATTERNS)
    css_contract = pattern_contract(styles_css, REQUIRED_STATIC_CSS_LAYOUT_PATTERNS)

    focused_contracts = {
        "home_entry": pattern_contract(
            index_html,
            (
                'id="homeButton"',
                'aria-label="Home"',
                'id="homeForm"',
                'id="homeInput"',
                "궁금한 게 있으면 질문하세요",
                'id="homeSampleList"',
            ),
        ),
        "desktop_workbench": pattern_contract(
            styles_css,
            (
                "grid-template-columns: 276px minmax(0, 1fr) 304px;",
                "grid-template-rows: auto auto minmax(132px, 1fr) var(--result-grid-height) auto;",
                "height: calc(100dvh - 46px);",
            ),
        ),
        "table_scroll_safety": pattern_contract(
            styles_css,
            (
                ".data-grid-wrap",
                "overflow: auto;",
                "overscroll-behavior: contain;",
                "position: sticky;",
                "min-width: 720px;",
            ),
        ),
        "chat_trace_panel": pattern_contract(
            index_html + "\n" + styles_css,
            (
                'id="chatQuestion"',
                'id="chatSummary"',
                'id="miniResult"',
                'id="traceList"',
                ".chat-scroll",
                "overflow: auto;",
            ),
        ),
        "responsive_breakpoints": pattern_contract(
            styles_css,
            (
                "@media (max-width: 1180px)",
                "@media (max-width: 820px)",
                "@media (max-width: 560px)",
                ".ai-pane {\n    grid-column: 1 / -1;",
                ".rail {\n    display: none;",
            ),
        ),
        "dynamic_result_height": pattern_contract(
            app_js,
            (
                'window.addEventListener("resize", syncResultGridHeight)',
                'dataPane.style.setProperty("--result-grid-height"',
                "tableScrollHeight: table.scrollHeight",
            ),
        ),
    }
    all_contracts = {
        "html": html_contract,
        "app": app_contract,
        "css": css_contract,
        **focused_contracts,
    }
    return {
        "static_dir": str(STATIC_DIR),
        "checked_files": list(REQUIRED_STATIC_FILES),
        "missing_files": missing_files,
        "passed": not missing_files and all(contract["passed"] for contract in all_contracts.values()),
        "contracts": all_contracts,
    }


def validate_sql_for_evidence(
    *,
    db_path: str,
    sql: str,
    role: str,
    branch_id: int | None = None,
) -> Any:
    connection = connect_database(db_path)
    try:
        normalized_role = normalize_user_role(role)
        branch_scope_branch_id = branch_id if normalized_role == "branch_manager" else None
        return validate_sql(
            sql,
            allowed_tables=ROLE_TABLE_POLICY[normalized_role],
            connection=connection,
            branch_scope_branch_id=branch_scope_branch_id,
        )
    finally:
        connection.close()


def summarize_query_execution_result(result: QueryExecutionResult) -> dict[str, Any]:
    return {
        "columns": result.columns,
        "column_metadata": result.column_metadata,
        "row_count": len(result.rows),
        "rows_sample": result.rows[:5],
        "query_plan_summary": result.query_plan_summary,
        "pre_execution_row_count": result.pre_execution_row_count,
        "pre_execution_row_count_status": result.pre_execution_row_count_status,
        "pre_execution_check_ms": result.pre_execution_check_ms,
        "execution_ms": result.execution_ms,
        "error_issue": result.error_issue,
    }


def run_query_execution_sample(
    *,
    db_path: str,
    name: str,
    question: str,
    sql: str,
    role: str,
    branch_id: int,
    expect_empty: bool,
) -> dict[str, Any]:
    validation = validate_sql_for_evidence(db_path=db_path, sql=sql, role=role, branch_id=branch_id)
    execution_payload: dict[str, Any] | None = None
    execution_passed = False
    if validation.allowed:
        result = execution_backend_for_name().execute_validated_sql(
            db_path=db_path,
            sql=validation.sql,
            timeout_ms=QUERY_EXECUTION_SAMPLE_TIMEOUT_MS,
            allowed_tables=ROLE_TABLE_POLICY[normalize_user_role(role)],
        )
        execution_payload = summarize_query_execution_result(result)
        has_expected_row_state = (
            execution_payload["row_count"] == 0 if expect_empty else execution_payload["row_count"] > 0
        )
        execution_passed = (
            result.error_issue is None
            and bool(result.columns)
            and bool(result.column_metadata)
            and bool(result.query_plan_summary)
            and result.pre_execution_row_count_status == "checked"
            and has_expected_row_state
        )

    return {
        "name": name,
        "question": question,
        "role": role,
        "branch_id": branch_id if normalize_user_role(role) == "branch_manager" else None,
        "sql": sql,
        "expect_empty": expect_empty,
        "validation_allowed": validation.allowed,
        "validation_issues": list(validation.issues),
        "referenced_tables": list(validation.referenced_tables),
        "execution": execution_payload,
        "passed": validation.allowed and execution_passed,
    }


def build_query_execution_samples_artifact(
    *,
    db_path: str,
    branch_id: int,
) -> dict[str, Any]:
    ensure_demo_database(db_path)
    samples = [
        run_query_execution_sample(
            db_path=db_path,
            name="aggregate_result",
            question="지난 3개월간 지점별 신규 계좌 수 추이는?",
            role="sales_planning",
            branch_id=branch_id,
            expect_empty=False,
            sql=(
                "SELECT b.branch_name, STRFTIME('%Y-%m', a.opened_at) AS opened_month, "
                "COUNT(a.account_id) AS new_account_count "
                "FROM accounts a JOIN branches b ON a.branch_id = b.branch_id "
                "WHERE a.opened_at >= DATE('2026-06-24', '-3 months') "
                "GROUP BY b.branch_name, opened_month "
                "ORDER BY opened_month, b.branch_name "
                "LIMIT 100"
            ),
        ),
        run_query_execution_sample(
            db_path=db_path,
            name="empty_result",
            question="존재하지 않는 VOC 상태를 조회하면 어떻게 표시되는가?",
            role="compliance",
            branch_id=branch_id,
            expect_empty=True,
            sql=(
                "SELECT b.branch_name, COUNT(v.case_id) AS matching_voc_count "
                "FROM branches b LEFT JOIN voc_cases v "
                "ON v.branch_id = b.branch_id AND v.status = 'not_a_real_status' "
                "WHERE b.active_flag = 1 "
                "GROUP BY b.branch_name "
                "HAVING matching_voc_count > 0 "
                "LIMIT 100"
            ),
        ),
        run_query_execution_sample(
            db_path=db_path,
            name="branch_scoped_result",
            question="내 지점의 신규 계좌 수는?",
            role="branch_manager",
            branch_id=branch_id,
            expect_empty=False,
            sql=(
                "SELECT b.branch_name, COUNT(a.account_id) AS new_account_count "
                "FROM accounts a JOIN branches b ON a.branch_id = b.branch_id "
                f"WHERE a.branch_id = {branch_id} "
                "GROUP BY b.branch_name "
                "LIMIT 10"
            ),
        ),
    ]
    return {
        "backend": execution_backend_for_name().name,
        "db_path": db_path,
        "timeout_ms": QUERY_EXECUTION_SAMPLE_TIMEOUT_MS,
        "sample_total": len(samples),
        "passed": all(sample["passed"] for sample in samples),
        "failed_total": sum(1 for sample in samples if not sample["passed"]),
        "samples": samples,
    }


def build_role_policy_matrix_artifact(
    *,
    db_path: str,
    branch_id: int,
) -> dict[str, Any]:
    ensure_demo_database(db_path)
    roles: list[dict[str, Any]] = []
    for role in sorted(ROLE_TABLE_POLICY):
        selected_context = retrieve_schema("지난 3개월간 지점별 신규 계좌 수 추이는?", user_role=role)
        roles.append(
            {
                "role": role,
                "allowed_tables": sorted(ROLE_TABLE_POLICY[role]),
                "retrieved_tables_for_new_accounts": sorted(selected_context.allowed_table_names),
                "operational_tables_excluded": "query_audit_log" not in ROLE_TABLE_POLICY[role],
            }
        )

    probe_specs = [
        {
            "name": "sales_planning_allows_target_aggregate",
            "role": "sales_planning",
            "expected_allowed": True,
            "sql": (
                "SELECT b.branch_name, bt.target_month, SUM(bt.target_value) AS target_value "
                "FROM branch_targets bt JOIN branches b ON bt.branch_id = b.branch_id "
                "WHERE bt.metric_name = 'new_accounts' "
                "GROUP BY b.branch_name, bt.target_month "
                "LIMIT 100"
            ),
        },
        {
            "name": "compliance_blocks_accounts",
            "role": "compliance",
            "expected_allowed": False,
            "sql": "SELECT COUNT(account_id) AS account_count FROM accounts LIMIT 10",
        },
        {
            "name": "branch_manager_requires_branch_scope",
            "role": "branch_manager",
            "expected_allowed": False,
            "sql": (
                "SELECT b.branch_name, COUNT(a.account_id) AS new_account_count "
                "FROM accounts a JOIN branches b ON a.branch_id = b.branch_id "
                "GROUP BY b.branch_name "
                "LIMIT 10"
            ),
        },
        {
            "name": "branch_manager_allows_scoped_aggregate",
            "role": "branch_manager",
            "expected_allowed": True,
            "sql": (
                "SELECT b.branch_name, COUNT(a.account_id) AS new_account_count "
                "FROM accounts a JOIN branches b ON a.branch_id = b.branch_id "
                f"WHERE a.branch_id = {branch_id} "
                "GROUP BY b.branch_name "
                "LIMIT 10"
            ),
        },
        {
            "name": "schema_retrieval_excludes_role_disallowed_tables",
            "role": "compliance",
            "expected_allowed": True,
            "sql": "SELECT 1 AS retrieval_policy_check LIMIT 1",
            "retrieval_question": "지난 3개월간 지점별 신규 계좌 수 추이는?",
            "expected_missing_table": "accounts",
        },
        {
            "name": "operational_audit_table_blocked",
            "role": "sales_planning",
            "expected_allowed": False,
            "sql": "SELECT COUNT(audit_id) AS audit_count FROM query_audit_log LIMIT 10",
        },
    ]
    probes: list[dict[str, Any]] = []
    for spec in probe_specs:
        validation = validate_sql_for_evidence(
            db_path=db_path,
            sql=spec["sql"],
            role=spec["role"],
            branch_id=branch_id,
        )
        retrieved_tables: list[str] = []
        retrieval_passed = True
        if spec.get("retrieval_question"):
            context = retrieve_schema(spec["retrieval_question"], user_role=spec["role"])
            retrieved_tables = sorted(context.allowed_table_names)
            expected_missing_table = str(spec["expected_missing_table"])
            retrieval_passed = expected_missing_table not in retrieved_tables
        probes.append(
            {
                "name": spec["name"],
                "role": spec["role"],
                "expected_allowed": spec["expected_allowed"],
                "actual_allowed": validation.allowed,
                "validation_issues": list(validation.issues),
                "referenced_tables": list(validation.referenced_tables),
                "retrieved_tables": retrieved_tables,
                "passed": validation.allowed is spec["expected_allowed"] and retrieval_passed,
            }
        )

    return {
        "db_path": db_path,
        "role_total": len(roles),
        "roles": roles,
        "probe_total": len(probes),
        "failed_total": sum(1 for probe in probes if not probe["passed"]),
        "operational_tables_excluded_from_roles": all(role["operational_tables_excluded"] for role in roles),
        "passed": all(role["operational_tables_excluded"] for role in roles)
        and all(probe["passed"] for probe in probes),
        "probes": probes,
    }


def build_live_llm_generation_samples_artifact(
    *,
    db_path: str,
    role: str,
    branch_id: int,
    live_checks: bool,
) -> dict[str, Any]:
    core_cases = tuple(case for case in EVALUATION_CASES if evaluation_case_group(case) == "core")
    base_payload: dict[str, Any] = {
        "status": "not_run",
        "live_checks_enabled": live_checks,
        "required_core_cases": 5,
        "case_total": len(core_cases),
        "passed_cases": 0,
        "failed_cases": 0,
        "model": configured_llm_model(),
        "base_url": configured_llm_base_url(),
        "cases": [],
    }
    if not live_checks:
        return {
            **base_payload,
            "reason": "Live LLM checks were not requested for this evidence run.",
        }
    if len(core_cases) < 5:
        return {
            **base_payload,
            "status": "failed",
            "reason": f"Core demo case count is {len(core_cases)}, below required 5.",
        }
    if not llm_endpoint_configured():
        return {
            **base_payload,
            "status": "failed",
            "failed_cases": len(core_cases),
            "reason": "LLM endpoint is not configured.",
            "cases": [
                {
                    **build_live_prompt_contract_case(case=case, role=role, branch_id=branch_id),
                    "case_id": case.case_id,
                    "question": case.question,
                    "status": "failed",
                    "error": "LLM endpoint is not configured.",
                }
                for case in core_cases
            ],
        }

    ensure_demo_database(db_path)
    case_results: list[dict[str, Any]] = []
    connection = connect_database(db_path)
    try:
        for case in core_cases:
            case_results.append(
                run_live_llm_generation_sample_case(
                    case=case,
                    db_path=db_path,
                    connection=connection,
                    role=role,
                    branch_id=branch_id,
                )
            )
    finally:
        connection.close()

    passed_cases = sum(1 for item in case_results if item["status"] == "passed")
    return {
        **base_payload,
        "status": "passed" if passed_cases == len(core_cases) else "failed",
        "passed_cases": passed_cases,
        "failed_cases": len(core_cases) - passed_cases,
        "reason": "Core demo live LLM samples executed.",
        "cases": case_results,
    }


def build_live_prompt_contract_case(
    *,
    case: EvaluationCase,
    role: str,
    branch_id: int,
) -> dict[str, Any]:
    context = retrieve_schema(case.question, user_role=role)
    payload = build_llm_payload(
        case.question,
        context,
        model=configured_llm_model(),
        user_role=role,
        branch_id=branch_id,
    )
    payload_bytes = json.dumps(payload, ensure_ascii=False, sort_keys=True).encode("utf-8")
    user_context = json.loads(str(payload["messages"][1]["content"]))
    response_contract = user_context.get("response_contract", {})
    if not isinstance(response_contract, dict):
        response_contract = {}
    properties = response_contract.get("properties", {})
    if not isinstance(properties, dict):
        properties = {}
    assumptions_property = properties.get("assumptions", {})
    if not isinstance(assumptions_property, dict):
        assumptions_property = {}
    assumptions_items = assumptions_property.get("items", {})
    if not isinstance(assumptions_items, dict):
        assumptions_items = {}
    return {
        "prompt_payload_sha256": hashlib.sha256(payload_bytes).hexdigest(),
        "prompt_contract": {
            "model": payload["model"],
            "prompt_version": user_context.get("prompt_version"),
            "temperature": payload.get("temperature"),
            "top_p": payload.get("top_p"),
            "response_format": payload["response_format"],
            "response_contract_required": response_contract.get("required", []),
            "response_contract_checks": {
                "required_keys": response_contract.get("required") == [
                    "sql",
                    "reason",
                    "assumptions",
                ],
                "sql_is_string": properties.get("sql", {}).get("type") == "string"
                if isinstance(properties.get("sql", {}), dict)
                else False,
                "reason_is_string": properties.get("reason", {}).get("type") == "string"
                if isinstance(properties.get("reason", {}), dict)
                else False,
                "assumptions_is_string_array": assumptions_property.get("type") == "array"
                and assumptions_items.get("type") == "string",
            },
            "selected_table_names": [
                table["name"]
                for table in user_context.get("selected_schema", {}).get("allowed_tables", [])
                if isinstance(table, dict) and "name" in table
            ],
            "matched_metric_names": [
                metric["name"]
                for metric in user_context.get("matched_metrics", [])
                if isinstance(metric, dict) and "name" in metric
            ],
        },
    }


def build_llm_evaluation_diagnostics_artifact(
    *,
    profile: str | None,
    live_checks: bool,
    role: str,
    branch_id: int,
    readiness: dict[str, Any],
    external_readiness: dict[str, Any],
    prd_thresholds: dict[str, Any],
    evaluation_summary: dict[str, Any],
    evaluation_diff_summary: dict[str, Any],
    live_llm_generation_samples: dict[str, Any],
) -> dict[str, Any]:
    endpoint = configured_llm_base_url()
    try:
        timeout_seconds: float | str = llm_timeout_seconds()
        timeout_valid = True
    except LLMGenerationError as exc:
        timeout_seconds = str(exc)
        timeout_valid = False

    diff_cases = evaluation_diff_summary.get("cases", [])
    failure_reason_counts: dict[str, int] = {}
    for case in diff_cases:
        for reason in case.get("failure_reasons", []):
            failure_reason_counts[reason] = failure_reason_counts.get(reason, 0) + 1

    missing_external_items = external_readiness.get("missing_verification_commands", [])
    next_commands = [
        {
            "name": item["name"],
            "command": item["command"],
            "environment_keys": item["environment_keys"],
        }
        for item in missing_external_items
    ]
    if not next_commands and not prd_thresholds["passed"]:
        selected_profile = profile or "poc"
        next_commands.append(
            {
                "name": "prd_evaluation_gate",
                "command": f"python -m im_one_agent.evidence --profile {selected_profile} --live-checks --strict",
                "environment_keys": [
                    "OPENAI_API_KEY",
                    "IM_ONE_LLM_MODEL",
                    "IM_ONE_LLM_BASE_URL",
                    "IM_ONE_LLM_TIMEOUT",
                ],
            }
        )

    live_status = live_llm_generation_samples.get("status", "unknown")
    endpoint_configured = llm_endpoint_configured()
    action_required = (
        readiness["summary"]["required_failed"] > 0
        or external_readiness["missing_total"] > 0
        or not prd_thresholds["passed"]
        or live_status != "passed"
    )
    return {
        "status": "action_required" if action_required else "passed",
        "profile": profile,
        "live_checks_enabled": live_checks,
        "role": role,
        "branch_id": branch_id,
        "llm_endpoint": {
            "configured": endpoint_configured,
            "api_key_configured": bool(os.getenv("OPENAI_API_KEY")),
            "local_no_auth_enabled": local_llm_no_auth_enabled(endpoint),
            "base_url": endpoint,
            "model": configured_llm_model(),
            "timeout_seconds": timeout_seconds,
            "timeout_valid": timeout_valid,
        },
        "live_llm_generation": {
            "status": live_status,
            "case_total": live_llm_generation_samples.get("case_total", 0),
            "passed_cases": live_llm_generation_samples.get("passed_cases", 0),
            "failed_cases": live_llm_generation_samples.get("failed_cases", 0),
            "reason": live_llm_generation_samples.get("reason", ""),
        },
        "evaluation_gate": {
            "passed": prd_thresholds["passed"],
            "failures": prd_thresholds["failures"],
            "metrics": prd_thresholds["metrics"],
            "targets": prd_thresholds["targets"],
            "summary": {
                "total_cases": evaluation_summary["total_cases"],
                "passed_cases": evaluation_summary["passed_cases"],
                "failed_cases": evaluation_summary["failed_cases"],
                "core_demo_success_rate": evaluation_summary["core_demo_success_rate"],
                "non_blocked_execution_success_rate": evaluation_summary[
                    "non_blocked_execution_success_rate"
                ],
                "blocked_rejection_rate": evaluation_summary["blocked_rejection_rate"],
                "latency_success_rate": evaluation_summary["latency_success_rate"],
            },
        },
        "failure_analysis": {
            "diff_case_total": evaluation_diff_summary["diff_case_total"],
            "failed_total": evaluation_diff_summary["failed_total"],
            "llm_generation_failure_total": evaluation_diff_summary["llm_generation_failure_total"],
            "failure_reason_counts": dict(sorted(failure_reason_counts.items())),
            "sample_failed_cases": [
                {
                    "case_id": case["case_id"],
                    "group": case["group"],
                    "failure_reasons": case["failure_reasons"],
                    "issues": case["issues"],
                }
                for case in diff_cases[:10]
            ],
        },
        "remaining_gates": {
            "readiness_required_failed_names": readiness["summary"]["required_failed_names"],
            "external_missing_names": external_readiness["missing_names"],
            "prd_threshold_failures": prd_thresholds["failures"],
        },
        "next_commands": next_commands,
    }


def run_live_llm_generation_sample_case(
    *,
    case: EvaluationCase,
    db_path: str,
    connection: sqlite3.Connection,
    role: str,
    branch_id: int,
) -> dict[str, Any]:
    started_at = perf_counter()
    context = retrieve_schema(case.question, user_role=role)
    base_case: dict[str, Any] = {
        "case_id": case.case_id,
        "question": case.question,
        "intent": case.intent,
        "expected_metric": case.expected_metric,
        "required_tables": list(case.required_tables),
        "expected_result_shape": list(case.expected_result_shape),
        "selected_tables": list(context.allowed_table_names),
        "matched_metrics": [metric.name for metric in context.matched_metrics],
        "retrieval_confidence": context.retrieval_confidence,
        **build_live_prompt_contract_case(case=case, role=role, branch_id=branch_id),
    }
    try:
        generated = generate_sql_with_llm(
            case.question,
            context,
            user_role=role,
            branch_id=branch_id,
        )
    except LLMGenerationError as exc:
        return {
            **base_case,
            "status": "failed",
            "elapsed_ms": round((perf_counter() - started_at) * 1000, 2),
            "error": str(exc),
        }

    validation = validate_sql(
        generated.sql,
        allowed_tables=context.allowed_table_names,
        connection=connection,
    )
    missing_tables = tuple(table for table in case.required_tables if table not in validation.referenced_tables)
    columns: tuple[str, ...] = ()
    row_count = 0
    execution_error = ""
    execution_payload: dict[str, Any] | None = None
    if validation.allowed:
        execution_result = execution_backend_for_name().execute_validated_sql(
            db_path=db_path,
            sql=validation.sql,
            timeout_ms=LIVE_LLM_QUERY_TIMEOUT_MS,
            allowed_tables=context.allowed_table_names,
        )
        execution_payload = summarize_query_execution_result(execution_result)
        columns = tuple(execution_result.columns)
        row_count = len(execution_result.rows)
        execution_error = execution_result.error_issue or ""
    missing_columns = tuple(column for column in case.expected_result_shape if column not in columns)
    elapsed_ms = round((perf_counter() - started_at) * 1000, 2)
    case_passed = (
        generated.engine == "llm"
        and generated.prompt_version == PROMPT_VERSION
        and validation.allowed
        and execution_payload is not None
        and not missing_tables
        and not missing_columns
        and not execution_error
        and row_count > 0
        and execution_payload["pre_execution_row_count_status"] == "checked"
        and elapsed_ms <= 10000
    )
    return {
        **base_case,
        "status": "passed" if case_passed else "failed",
        "elapsed_ms": elapsed_ms,
        "generation_engine": generated.engine,
        "model": generated.model,
        "prompt_version": generated.prompt_version,
        "reason": generated.reason,
        "assumptions": list(generated.assumptions),
        "sql": generated.sql,
        "validation_allowed": validation.allowed,
        "validation_issues": list(validation.issues),
        "referenced_tables": list(validation.referenced_tables),
        "missing_tables": list(missing_tables),
        "columns": list(columns),
        "missing_columns": list(missing_columns),
        "row_count": row_count,
        "execution": execution_payload,
        "execution_error": execution_error,
    }


def pattern_contract(content: str, patterns: tuple[str, ...]) -> dict[str, Any]:
    missing = [pattern for pattern in patterns if pattern not in content]
    return {
        "passed": not missing,
        "total": len(patterns),
        "matched": len(patterns) - len(missing),
        "missing": missing,
    }


def build_evidence_gate_payload(
    readiness: dict[str, Any],
    external_readiness: dict[str, Any],
    prd_thresholds: dict[str, Any],
) -> dict[str, Any]:
    failures: list[dict[str, Any]] = []
    readiness_required_failed = int(readiness["summary"]["required_failed"])
    external_missing_total = int(external_readiness["missing_total"])

    if readiness_required_failed:
        failures.append(
            {
                "name": "readiness_required_failures",
                "count": readiness_required_failed,
                "details": readiness["summary"]["required_failed_names"],
            }
        )
    if external_missing_total:
        failures.append(
            {
                "name": "external_readiness_missing",
                "count": external_missing_total,
                "details": external_readiness["missing_names"],
            }
        )
    if not prd_thresholds["passed"]:
        failures.append(
            {
                "name": "prd_evaluation_gate_failed",
                "count": len(prd_thresholds["failures"]),
                "details": prd_thresholds["failures"],
            }
        )

    return {
        "passed": not failures,
        "status": "passed" if not failures else "failed",
        "failure_count": len(failures),
        "failures": failures,
    }


def completion_status_for_requirement(requirement: dict[str, Any]) -> str:
    statuses = [check["status"] for check in requirement.get("preflight_checks", [])]
    if any(status == "failed" for status in statuses):
        return "failed"
    if any(status == "not_run" for status in statuses):
        return "not_run"
    if statuses and all(status == "passed" for status in statuses):
        return "passed"
    return "unknown"


def build_completion_blocking_conditions(
    evidence_gate: dict[str, Any],
    external_readiness: dict[str, Any],
    prd_thresholds: dict[str, Any],
) -> list[dict[str, Any]]:
    blocking_conditions: list[dict[str, Any]] = []
    for failure in evidence_gate.get("failures", []):
        condition: dict[str, Any] = {
            "name": failure["name"],
            "count": failure["count"],
            "details": failure["details"],
        }
        if failure["name"] == "external_readiness_missing":
            condition["verification_commands"] = external_readiness.get("missing_verification_commands", [])
        if failure["name"] == "prd_evaluation_gate_failed":
            condition["thresholds"] = prd_thresholds.get("targets", {})
        blocking_conditions.append(condition)
    return blocking_conditions


def build_completion_audit_payload(
    *,
    generated_at: str,
    profile: str | None,
    live_checks: bool,
    role: str,
    branch_id: int,
    readiness: dict[str, Any],
    external_readiness: dict[str, Any],
    prd_traceability: dict[str, Any],
    prd_thresholds: dict[str, Any],
    evidence_gate: dict[str, Any],
) -> dict[str, Any]:
    requirements: list[dict[str, Any]] = []
    for requirement in prd_traceability["requirements"]:
        preflight_checks = list(requirement["preflight_checks"])
        if requirement["requirement_id"] == "FR-012":
            preflight_checks.append(
                {
                    "name": "prd_evaluation_gate",
                    "status": "passed" if prd_thresholds["passed"] else "failed",
                    "passed": prd_thresholds["passed"],
                    "required": True,
                    "detail": "PRD evaluation thresholds passed."
                    if prd_thresholds["passed"]
                    else "; ".join(prd_thresholds["failures"]),
                    "targets": prd_thresholds["targets"],
                    "metrics": prd_thresholds["metrics"],
                }
            )
        audited_requirement = {**requirement, "preflight_checks": preflight_checks}
        status = completion_status_for_requirement(audited_requirement)
        checks_requiring_attention = [
            check
            for check in preflight_checks
            if check["status"] in {"failed", "not_run", "unknown"}
        ]
        requirements.append(
            {
                "requirement_id": requirement["requirement_id"],
                "title": requirement["title"],
                "category": requirement["category"],
                "status": status,
                "implementation_artifacts": requirement["implementation_artifacts"],
                "verification_artifacts": requirement["verification_artifacts"],
                "checks_requiring_attention": checks_requiring_attention,
                "preflight_checks": preflight_checks,
            }
        )

    status_counts = {
        "passed": sum(1 for requirement in requirements if requirement["status"] == "passed"),
        "failed": sum(1 for requirement in requirements if requirement["status"] == "failed"),
        "not_run": sum(1 for requirement in requirements if requirement["status"] == "not_run"),
        "unknown": sum(1 for requirement in requirements if requirement["status"] == "unknown"),
    }
    blocking_conditions = build_completion_blocking_conditions(
        evidence_gate,
        external_readiness,
        prd_thresholds,
    )
    requirement_blockers = [
        {
            "requirement_id": requirement["requirement_id"],
            "title": requirement["title"],
            "status": requirement["status"],
            "checks_requiring_attention": [
                check["name"] for check in requirement["checks_requiring_attention"]
            ],
        }
        for requirement in requirements
        if requirement["status"] != "passed"
    ]
    if requirement_blockers:
        blocking_conditions.append(
            {
                "name": "requirement_completion_incomplete",
                "count": len(requirement_blockers),
                "details": requirement_blockers,
            }
        )
    external_items = [
        {
            "name": item["name"],
            "title": item["title"],
            "status": item["status"],
            "required_for_profile": item["required_for_profile"],
            "verification_command": item["verification_command"],
            "environment_keys": item["environment_keys"],
            "evidence_required": item["evidence_required"],
        }
        for item in external_readiness["items"]
    ]
    passed = evidence_gate["passed"] and not requirement_blockers
    status = "passed" if passed else "failed"

    return {
        "generated_at": generated_at,
        "profile": profile,
        "live_checks_enabled": live_checks,
        "role": role,
        "branch_id": branch_id,
        "passed": passed,
        "status": status,
        "summary": {
            "requirement_total": len(requirements),
            "requirement_status_counts": status_counts,
            "requirement_incomplete_total": len(requirement_blockers),
            "readiness_required_failed": readiness["summary"]["required_failed"],
            "external_required_total": external_readiness["required_total"],
            "external_missing_total": external_readiness["missing_total"],
            "prd_evaluation_passed": prd_thresholds["passed"],
            "blocking_condition_count": len(blocking_conditions),
        },
        "blocking_conditions": blocking_conditions,
        "requirements": requirements,
        "external_readiness": {
            "required_total": external_readiness["required_total"],
            "verified_total": external_readiness["verified_total"],
            "missing_total": external_readiness["missing_total"],
            "missing_names": external_readiness["missing_names"],
            "missing_verification_commands": external_readiness["missing_verification_commands"],
            "items": external_items,
        },
        "prd_evaluation_gate": prd_thresholds,
        "evidence_gate": evidence_gate,
    }


def external_readiness_verification_command(item: dict[str, Any], profile: str | None) -> str:
    target_profile = profile if profile in item["profiles"] else item["profiles"][0]
    return str(item["verification_command"]).format(profile=target_profile)


def build_external_readiness_payload(
    readiness: dict[str, Any],
    profile: str | None,
    live_checks: bool,
) -> dict[str, Any]:
    checks_by_name = {check["name"]: check for check in readiness.get("checks", [])}
    items: list[dict[str, Any]] = []

    for item in EXTERNAL_READINESS_ITEMS:
        required_for_profile = profile in item["profiles"]
        verification_command = external_readiness_verification_command(item, profile)
        evidence_checks: list[dict[str, Any]] = []
        missing_required = False
        not_run_required = False

        for check_name in item["checks"]:
            check = checks_by_name.get(check_name)
            if check is None:
                evidence_checks.append(
                    {
                        "name": check_name,
                        "status": "not_run",
                        "passed": None,
                        "required": required_for_profile,
                        "detail": "This check was not executed in the current evidence run.",
                        "action": PREFLIGHT_NEXT_ACTIONS.get(check_name, ""),
                    }
                )
                if required_for_profile:
                    not_run_required = True
                continue

            passed = bool(check.get("passed"))
            evidence_checks.append(
                {
                    "name": check_name,
                    "status": "passed" if passed else "failed",
                    "passed": passed,
                    "required": check.get("required"),
                    "detail": check.get("detail"),
                    "action": PREFLIGHT_NEXT_ACTIONS.get(check_name, ""),
                }
            )
            if required_for_profile and not passed:
                missing_required = True

        if not required_for_profile:
            status = "not_required_for_profile"
        elif missing_required:
            status = "missing_evidence"
        elif not_run_required:
            status = "not_run"
        else:
            status = "verified"

        items.append(
            {
                "name": item["name"],
                "title": item["title"],
                "status": status,
                "required_for_profile": required_for_profile,
                "profiles": list(item["profiles"]),
                "environment_keys": list(item["environment_keys"]),
                "verification_command": verification_command,
                "evidence_required": item["evidence_required"],
                "checks": evidence_checks,
            }
        )

    required_items = [item for item in items if item["required_for_profile"]]
    verified_items = [item for item in required_items if item["status"] == "verified"]
    missing_items = [
        item
        for item in required_items
        if item["status"] in {"missing_evidence", "not_run"}
    ]

    return {
        "profile": profile,
        "live_checks_enabled": live_checks,
        "required_total": len(required_items),
        "verified_total": len(verified_items),
        "missing_total": len(missing_items),
        "missing_names": [item["name"] for item in missing_items],
        "missing_verification_commands": [
            {
                "name": item["name"],
                "command": item["verification_command"],
                "environment_keys": item["environment_keys"],
            }
            for item in missing_items
        ],
        "items": items,
    }


def shell_arg(value: object) -> str:
    return shlex.quote(str(value))


def contextualized_external_command(command: str, context: dict[str, Any] | None) -> str:
    if not context:
        return command

    if "python -m im_one_agent.evidence" in command:
        return " ".join(
            [
                command,
                "--output-dir",
                shell_arg(context["output_dir"]),
                "--db-path",
                shell_arg(context["db_path"]),
                "--audit-path",
                shell_arg(context["audit_path"]),
                "--role",
                shell_arg(context["role"]),
                "--branch-id",
                shell_arg(context["branch_id"]),
            ]
        )
    if "python -m im_one_agent.preflight" in command:
        return " ".join([command, "--db-path", shell_arg(context["db_path"])])
    return command


def build_external_readiness_command_script(
    external_readiness: dict[str, Any],
    context: dict[str, Any] | None = None,
) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by iM One NL2SQL evidence pack.",
        f"# Profile: {external_readiness.get('profile') or 'local'}",
        f"# Required external items: {external_readiness.get('required_total', 0)}",
        f"# Missing external items: {external_readiness.get('missing_total', 0)}",
        "",
    ]
    if context:
        lines.extend(
            [
                f"# Evidence output dir: {context['output_dir']}",
                f"# DB path: {context['db_path']}",
                f"# Audit path: {context['audit_path']}",
                f"# Role: {context['role']}",
                f"# Branch ID: {context['branch_id']}",
                "# Case filters are not carried over; external gate replay should generate full PRD evidence.",
                "",
            ]
        )
    missing_commands = external_readiness.get("missing_verification_commands", [])
    if not missing_commands:
        lines.extend(
            [
                'echo "No missing external readiness commands for this evidence profile."',
                "",
            ]
        )
        return "\n".join(lines)

    items_by_name = {item["name"]: item for item in external_readiness.get("items", [])}
    emitted_commands: set[str] = set()
    for command_item in missing_commands:
        name = command_item["name"]
        command = contextualized_external_command(command_item["command"], context)
        item = items_by_name.get(name, {})
        title = item.get("title", name)
        evidence_required = item.get("evidence_required", "")
        environment_keys = ", ".join(command_item.get("environment_keys", []))

        lines.extend(
            [
                f'echo "==> {name}: {title}"',
                f"# Environment keys: {environment_keys}",
            ]
        )
        if evidence_required:
            lines.append(f"# Evidence required: {evidence_required}")
        if command in emitted_commands:
            lines.append("# Skipped duplicate command already emitted above.")
        else:
            lines.append(command)
            emitted_commands.add(command)
        lines.append("")

    return "\n".join(lines)


def build_index_markdown(manifest: dict[str, Any]) -> str:
    summary = manifest["summary"]
    files = manifest["files"]
    readiness_next_actions = summary.get("readiness_next_actions", [])
    lines = [
        "# iM One NL2SQL Evidence Pack",
        "",
        f"- Generated at: {manifest['generated_at']}",
        f"- Readiness profile: {manifest['profile'] or 'local'}",
        f"- Live checks: {'enabled' if manifest['live_checks_enabled'] else 'disabled'}",
        f"- Role: {manifest['role']}",
        f"- Branch ID: {manifest['branch_id']}",
        "",
        "## Summary",
        "",
        "| Item | Value |",
        "| --- | ---: |",
        f"| Readiness required failures | {summary['readiness_required_failed']} |",
        f"| Evaluation cases | {summary['evaluation_total_cases']} |",
        f"| Evaluation passed | {summary['evaluation_passed_cases']} |",
        f"| Blocked rejection rate | {summary['blocked_rejection_rate'] * 100:.1f}% |",
        f"| Verified questions | {summary['verified_total']} |",
        f"| Catalog governance issues | {summary['catalog_issue_count']} |",
        "",
    ]
    if readiness_next_actions:
        lines.extend(["## Readiness Next Actions", ""])
        for item in readiness_next_actions:
            required_label = "required" if item.get("required") else "optional"
            lines.append(f"- `{item['name']}` ({required_label}): {item['action']}")
        lines.append("")
    evidence_gate = summary.get("evidence_gate", {})
    if evidence_gate:
        lines.extend(
            [
                "## Evidence Gate",
                "",
                f"- Status: {evidence_gate['status']}",
                f"- Failure groups: {evidence_gate['failure_count']}",
            ]
        )
        for failure in evidence_gate["failures"]:
            details = ", ".join(str(detail) for detail in failure["details"])
            lines.append(f"- `{failure['name']}` ({failure['count']}): {details}")
        lines.append("")
    external_readiness = summary.get("external_readiness", {})
    if external_readiness:
        lines.extend(
            [
                "## External Readiness",
                "",
                f"- Required external items: {external_readiness['required_total']}",
                f"- Verified external items: {external_readiness['verified_total']}",
                f"- Missing external items: {external_readiness['missing_total']}",
            ]
        )
        if external_readiness["missing_names"]:
            lines.append("- Missing: " + ", ".join(f"`{name}`" for name in external_readiness["missing_names"]))
        missing_commands = external_readiness.get("missing_verification_commands", [])
        if missing_commands:
            lines.extend(["", "Missing verification commands:"])
            for item in missing_commands:
                env_keys = ", ".join(f"`{key}`" for key in item["environment_keys"])
                lines.append(f"- `{item['name']}`: `{item['command']}`")
                lines.append(f"  Environment keys: {env_keys}")
        lines.append("")
    traceability = summary.get("prd_traceability", {})
    if traceability:
        lines.extend(
            [
                "## PRD Traceability",
                "",
                f"- Functional requirements mapped: {traceability['functional_total']}",
                f"- Nonfunctional requirements mapped: {traceability['nonfunctional_total']}",
                f"- Evidence items: {traceability['evidence_items']}",
                "",
            ]
        )
    prd_thresholds = summary.get("prd_thresholds", {})
    if prd_thresholds:
        lines.extend(
            [
                "## PRD Evaluation Gate",
                "",
                f"- Status: {'passed' if prd_thresholds['passed'] else 'failed'}",
            ]
        )
        if prd_thresholds["failures"]:
            lines.extend(f"- {failure}" for failure in prd_thresholds["failures"])
        lines.append("")
    completion_audit = summary.get("completion_audit", {})
    if completion_audit:
        lines.extend(
            [
                "## Completion Audit",
                "",
                f"- Status: {completion_audit['status']}",
                f"- PRD requirements passed: {completion_audit['requirement_passed']}/{completion_audit['requirement_total']}",
                f"- Blocking conditions: {completion_audit['blocking_condition_count']}",
                f"- Artifact: `{files['completion_audit']}`",
                "",
            ]
        )
    audit_log = summary.get("audit_log", {})
    if audit_log:
        lines.extend(
            [
                "## Audit Log Evidence",
                "",
                f"- Events: {audit_log['event_count']}",
                f"- Source: `{audit_log['source_path']}`",
                f"- Artifact: `{files['audit_log']}`",
                f"- Summary: `{files['audit_summary']}`",
                f"- Database audit events: {summary.get('database_audit_log', {}).get('event_count', 0)}",
                f"- Database artifact: `{files['database_audit_log']}`",
                "",
            ]
        )
    sql_validation = summary.get("sql_validation_probes", {})
    if sql_validation:
        lines.extend(
            [
                "## SQL Validation Evidence",
                "",
                f"- Status: {'passed' if sql_validation['passed'] else 'failed'}",
                f"- Probes: {sql_validation['probe_total']}",
                f"- Failed probes: {sql_validation['failed_total']}",
                f"- Artifact: `{files['sql_validation_probes']}`",
                "",
            ]
        )
    schema_retrieval = summary.get("schema_retrieval_probes", {})
    if schema_retrieval:
        lines.extend(
            [
                "## Schema Retrieval Evidence",
                "",
                f"- Status: {'passed' if schema_retrieval['passed'] else 'failed'}",
                f"- Probes: {schema_retrieval['probe_total']}",
                f"- Failed probes: {schema_retrieval['failed_total']}",
                f"- Artifact: `{files['schema_retrieval_probes']}`",
                "",
            ]
        )
    query_execution_samples = summary.get("query_execution_samples", {})
    if query_execution_samples:
        lines.extend(
            [
                "## Query Execution Evidence",
                "",
                f"- Status: {'passed' if query_execution_samples['passed'] else 'failed'}",
                f"- Backend: `{query_execution_samples['backend']}`",
                f"- Samples: {query_execution_samples['sample_total']}",
                f"- Failed samples: {query_execution_samples['failed_total']}",
                f"- Artifact: `{files['query_execution_samples']}`",
                "",
            ]
        )
    role_policy_matrix = summary.get("role_policy_matrix", {})
    if role_policy_matrix:
        lines.extend(
            [
                "## Role Policy Evidence",
                "",
                f"- Status: {'passed' if role_policy_matrix['passed'] else 'failed'}",
                f"- Roles: {role_policy_matrix['role_total']}",
                f"- Probes: {role_policy_matrix['probe_total']}",
                f"- Failed probes: {role_policy_matrix['failed_total']}",
                f"- Artifact: `{files['role_policy_matrix']}`",
                "",
            ]
        )
    llm_prompt_contract = summary.get("llm_prompt_contract", {})
    if llm_prompt_contract:
        lines.extend(
            [
                "## LLM Prompt Contract Evidence",
                "",
                f"- Prompt version: `{llm_prompt_contract['prompt_version']}`",
                f"- Selected tables: {', '.join(f'`{name}`' for name in llm_prompt_contract['selected_table_names'])}",
                f"- Matched metrics: {', '.join(f'`{name}`' for name in llm_prompt_contract['matched_metric_names'])}",
                f"- Core demo prompt contracts: {llm_prompt_contract['core_demo_contract_total']}",
                f"- Sanitization passed: {'yes' if llm_prompt_contract['sanitization_passed'] else 'no'}",
                f"- Artifact: `{files['llm_prompt_contract']}`",
                "",
            ]
        )
    live_llm_generation_samples = summary.get("live_llm_generation_samples", {})
    if live_llm_generation_samples:
        lines.extend(
            [
                "## Live LLM Generation Evidence",
                "",
                f"- Status: {live_llm_generation_samples['status']}",
                f"- Live checks: {'enabled' if live_llm_generation_samples['live_checks_enabled'] else 'disabled'}",
                f"- Core cases: {live_llm_generation_samples['passed_cases']}/{live_llm_generation_samples['case_total']} passed",
                f"- Artifact: `{files['live_llm_generation_samples']}`",
                "",
            ]
        )
    llm_evaluation_diagnostics = summary.get("llm_evaluation_diagnostics", {})
    if llm_evaluation_diagnostics:
        lines.extend(
            [
                "## LLM Evaluation Diagnostics",
                "",
                f"- Status: {llm_evaluation_diagnostics['status']}",
                f"- Endpoint configured: {'yes' if llm_evaluation_diagnostics['endpoint_configured'] else 'no'}",
                f"- LLM generation failures: {llm_evaluation_diagnostics['llm_generation_failure_total']}",
                f"- Diff cases: {llm_evaluation_diagnostics['diff_case_total']}",
                f"- Next commands: {llm_evaluation_diagnostics['next_command_total']}",
                f"- Artifact: `{files['llm_evaluation_diagnostics']}`",
                "",
            ]
        )
    result_explanation_samples = summary.get("result_explanation_samples", {})
    if result_explanation_samples:
        lines.extend(
            [
                "## Result Explanation Evidence",
                "",
                f"- Allowed sample validation: {'passed' if result_explanation_samples['allowed_validation_allowed'] else 'failed'}",
                f"- Blocked sample validation: {'blocked' if not result_explanation_samples['blocked_validation_allowed'] else 'allowed'}",
                f"- Coverage checks passed: {result_explanation_samples['coverage_passed']}/{result_explanation_samples['coverage_total']}",
                f"- Artifact: `{files['result_explanation_samples']}`",
                "",
            ]
        )
    evaluation_diff_summary = summary.get("evaluation_diff_summary", {})
    if evaluation_diff_summary:
        lines.extend(
            [
                "## Evaluation Diff Evidence",
                "",
                f"- Diff cases: {evaluation_diff_summary['diff_case_total']}",
                f"- Gold mismatches: {evaluation_diff_summary['gold_mismatched_total']}",
                f"- LLM generation failures: {evaluation_diff_summary['llm_generation_failure_total']}",
                f"- Artifact: `{files['evaluation_diff_summary']}`",
                "",
            ]
        )
    ui_layout_contract = summary.get("ui_layout_contract", {})
    if ui_layout_contract:
        lines.extend(
            [
                "## UI Layout Contract Evidence",
                "",
                f"- Status: {'passed' if ui_layout_contract['passed'] else 'failed'}",
                f"- Contracts passed: {ui_layout_contract['contracts_passed']}/{ui_layout_contract['contracts_total']}",
                f"- Checked files: {', '.join(f'`{name}`' for name in ui_layout_contract['checked_files'])}",
                f"- Artifact: `{files['ui_layout_contract']}`",
                "",
            ]
        )
    lines.extend(["## Files", ""])
    lines.extend(f"- `{label}`: `{path}`" for label, path in files.items())
    lines.append("")
    return "\n".join(lines)


def build_evidence_pack(args: argparse.Namespace) -> dict[str, Any]:
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    cases = select_cases(args)

    readiness = readiness_report(args.db_path, args.profile, args.live_checks)
    evaluation_results = run_evaluation(
        db_path=args.db_path,
        audit_path=args.audit_path,
        cases=cases,
        role=args.role,
        branch_id=args.branch_id,
    )
    evaluation_summary = build_evaluation_summary(evaluation_results, cases=cases)
    evaluation_diff_summary = build_evaluation_diff_summary(evaluation_results, cases=cases)
    prd_thresholds = build_prd_threshold_payload(evaluation_summary)
    verified_manifest = build_verified_question_manifest(role=args.role, branch_id=args.branch_id)
    catalog = build_catalog_payload(role=args.role)
    catalog_governance = build_catalog_governance_payload(role=args.role)
    audit_summary = build_audit_summary(Path(args.audit_path), db_path=args.db_path)
    database_audit_events = load_database_audit_events(args.db_path)
    sql_validation_probes = run_sql_validation_policy_probes(args.db_path)
    schema_retrieval_probes = run_schema_retrieval_policy_probes()
    query_execution_samples = build_query_execution_samples_artifact(
        db_path=args.db_path,
        branch_id=args.branch_id,
    )
    role_policy_matrix = build_role_policy_matrix_artifact(
        db_path=args.db_path,
        branch_id=args.branch_id,
    )
    llm_prompt_contract = build_llm_prompt_contract_artifact(args.role, args.branch_id)
    live_llm_generation_samples = build_live_llm_generation_samples_artifact(
        db_path=args.db_path,
        role=args.role,
        branch_id=args.branch_id,
        live_checks=args.live_checks,
    )
    external_readiness = build_external_readiness_payload(readiness, args.profile, args.live_checks)
    llm_evaluation_diagnostics = build_llm_evaluation_diagnostics_artifact(
        profile=args.profile,
        live_checks=args.live_checks,
        role=args.role,
        branch_id=args.branch_id,
        readiness=readiness,
        external_readiness=external_readiness,
        prd_thresholds=prd_thresholds,
        evaluation_summary=evaluation_summary,
        evaluation_diff_summary=evaluation_diff_summary,
        live_llm_generation_samples=live_llm_generation_samples,
    )
    result_explanation_samples = build_result_explanation_samples_artifact()
    ui_layout_contract = build_ui_layout_contract_artifact()
    prd_traceability = build_prd_traceability_payload(readiness)
    evidence_gate = build_evidence_gate_payload(readiness, external_readiness, prd_thresholds)
    generated_at = datetime.now(timezone.utc).isoformat()
    completion_audit = build_completion_audit_payload(
        generated_at=generated_at,
        profile=args.profile,
        live_checks=args.live_checks,
        role=args.role,
        branch_id=args.branch_id,
        readiness=readiness,
        external_readiness=external_readiness,
        prd_traceability=prd_traceability,
        prd_thresholds=prd_thresholds,
        evidence_gate=evidence_gate,
    )

    files = {
        "readiness": "readiness.json",
        "external_readiness": "external_readiness.json",
        "prd_traceability": "prd_traceability.json",
        "completion_audit": "completion_audit.json",
        "audit_log": "audit_log.jsonl",
        "audit_summary": "audit_summary.json",
        "database_audit_log": "database_audit_log.json",
        "sql_validation_probes": "sql_validation_probes.json",
        "schema_retrieval_probes": "schema_retrieval_probes.json",
        "query_execution_samples": "query_execution_samples.json",
        "role_policy_matrix": "role_policy_matrix.json",
        "llm_prompt_contract": "llm_prompt_contract.json",
        "live_llm_generation_samples": "live_llm_generation_samples.json",
        "llm_evaluation_diagnostics": "llm_evaluation_diagnostics.json",
        "result_explanation_samples": "result_explanation_samples.json",
        "ui_layout_contract": "ui_layout_contract.json",
        "evaluation_report": "evaluation_report.json",
        "evaluation_diff_summary": "evaluation_diff_summary.json",
        "evaluation_summary": "evaluation_summary.md",
        "verified_questions": "verified_questions.json",
        "catalog": "catalog.json",
        "catalog_governance": "catalog_governance.json",
        "external_readiness_commands": "external_readiness_commands.sh",
        "manifest": "manifest.json",
        "index": "README.md",
    }

    write_json(output_dir / files["readiness"], readiness)
    write_json(output_dir / files["external_readiness"], external_readiness)
    write_json(output_dir / files["prd_traceability"], prd_traceability)
    write_json(output_dir / files["completion_audit"], completion_audit)
    audit_log_summary = write_audit_log_artifact(args.audit_path, output_dir / files["audit_log"])
    write_json(output_dir / files["audit_summary"], audit_summary)
    write_json(output_dir / files["database_audit_log"], database_audit_events)
    write_json(output_dir / files["sql_validation_probes"], sql_validation_probes)
    write_json(output_dir / files["schema_retrieval_probes"], schema_retrieval_probes)
    write_json(output_dir / files["query_execution_samples"], query_execution_samples)
    write_json(output_dir / files["role_policy_matrix"], role_policy_matrix)
    write_json(output_dir / files["llm_prompt_contract"], llm_prompt_contract)
    write_json(output_dir / files["live_llm_generation_samples"], live_llm_generation_samples)
    write_json(output_dir / files["llm_evaluation_diagnostics"], llm_evaluation_diagnostics)
    write_json(output_dir / files["result_explanation_samples"], result_explanation_samples)
    write_json(output_dir / files["ui_layout_contract"], ui_layout_contract)
    write_evaluation_report(evaluation_results, output_dir / files["evaluation_report"], cases=cases)
    write_evaluation_diff_summary(evaluation_results, output_dir / files["evaluation_diff_summary"], cases=cases)
    write_evaluation_markdown_summary(evaluation_results, output_dir / files["evaluation_summary"], cases=cases)
    write_json(output_dir / files["verified_questions"], verified_manifest)
    write_json(output_dir / files["catalog"], catalog)
    write_json(output_dir / files["catalog_governance"], catalog_governance)
    external_commands_path = output_dir / files["external_readiness_commands"]
    command_context = {
        "output_dir": args.output_dir,
        "db_path": args.db_path,
        "audit_path": args.audit_path,
        "role": args.role,
        "branch_id": args.branch_id,
    }
    external_commands_path.write_text(
        build_external_readiness_command_script(external_readiness, context=command_context),
        encoding="utf-8",
    )
    external_commands_path.chmod(0o755)

    readiness_next_actions = readiness["next_actions"] + build_live_check_next_actions(args.profile, args.live_checks)
    manifest: dict[str, Any] = {
        "generated_at": generated_at,
        "profile": args.profile,
        "live_checks_enabled": args.live_checks,
        "role": args.role,
        "branch_id": args.branch_id,
        "db_path": args.db_path,
        "audit_path": args.audit_path,
        "summary": {
            "readiness_required_failed": readiness["summary"]["required_failed"],
            "readiness_required_failed_names": readiness["summary"]["required_failed_names"],
            "readiness_next_actions": readiness_next_actions,
            "evidence_gate": evidence_gate,
            "external_readiness": {
                "required_total": external_readiness["required_total"],
                "verified_total": external_readiness["verified_total"],
                "missing_total": external_readiness["missing_total"],
                "missing_names": external_readiness["missing_names"],
                "missing_verification_commands": external_readiness["missing_verification_commands"],
            },
            "prd_traceability": {
                "functional_total": prd_traceability["functional_total"],
                "nonfunctional_total": prd_traceability["nonfunctional_total"],
                "evidence_items": prd_traceability["evidence_items"],
            },
            "completion_audit": {
                "status": completion_audit["status"],
                "passed": completion_audit["passed"],
                "requirement_total": completion_audit["summary"]["requirement_total"],
                "requirement_passed": completion_audit["summary"]["requirement_status_counts"]["passed"],
                "blocking_condition_count": completion_audit["summary"]["blocking_condition_count"],
            },
            "audit_log": audit_log_summary,
            "audit_summary": {
                "total": audit_summary["total"],
                "source": audit_summary["source"],
                "executed_count": audit_summary["executed_count"],
                "blocked_count": audit_summary["blocked_count"],
                "failed_count": audit_summary["failed_count"],
                "by_execution_status": audit_summary["by_execution_status"],
                "by_validation_status": audit_summary["by_validation_status"],
            },
            "database_audit_log": {
                "source": "query_audit_log",
                "source_path": args.db_path,
                "artifact_path": files["database_audit_log"],
                "event_count": len(database_audit_events),
            },
            "sql_validation_probes": {
                "passed": sql_validation_probes["passed"],
                "probe_total": sql_validation_probes["probe_total"],
                "failed_total": sql_validation_probes["failed_total"],
                "failures": sql_validation_probes["failures"],
            },
            "schema_retrieval_probes": {
                "passed": schema_retrieval_probes["passed"],
                "probe_total": schema_retrieval_probes["probe_total"],
                "failed_total": schema_retrieval_probes["failed_total"],
                "failures": schema_retrieval_probes["failures"],
            },
            "query_execution_samples": {
                "passed": query_execution_samples["passed"],
                "backend": query_execution_samples["backend"],
                "sample_total": query_execution_samples["sample_total"],
                "failed_total": query_execution_samples["failed_total"],
                "timeout_ms": query_execution_samples["timeout_ms"],
            },
            "role_policy_matrix": {
                "passed": role_policy_matrix["passed"],
                "role_total": role_policy_matrix["role_total"],
                "probe_total": role_policy_matrix["probe_total"],
                "failed_total": role_policy_matrix["failed_total"],
                "operational_tables_excluded_from_roles": role_policy_matrix[
                    "operational_tables_excluded_from_roles"
                ],
            },
            "llm_prompt_contract": {
                "prompt_version": llm_prompt_contract["prompt_version"],
                "selected_table_names": llm_prompt_contract["user_context"]["selected_table_names"],
                "matched_metric_names": [
                    metric["name"]
                    for metric in llm_prompt_contract["user_context"]["matched_metrics"]
                ],
                "core_demo_contract_total": len(llm_prompt_contract["core_demo_contracts"]),
                "core_demo_contracts_passed": all(
                    contract["selected_schema_only"]
                    and contract["matched_metric_names"]
                    and contract["dataset_classification"] == "synthetic_poc"
                    and contract["operational_tables_removed"]
                    for contract in llm_prompt_contract["core_demo_contracts"]
                ),
                "sanitization_passed": all(llm_prompt_contract["sanitization_checks"].values()),
                "response_contract_checks_passed": all(
                    llm_prompt_contract["response_contract_checks"].values()
                ),
                "system_prompt_checks_passed": all(llm_prompt_contract["system_prompt_checks"].values()),
            },
            "live_llm_generation_samples": {
                "status": live_llm_generation_samples["status"],
                "live_checks_enabled": live_llm_generation_samples["live_checks_enabled"],
                "case_total": live_llm_generation_samples["case_total"],
                "passed_cases": live_llm_generation_samples["passed_cases"],
                "failed_cases": live_llm_generation_samples["failed_cases"],
            },
            "llm_evaluation_diagnostics": {
                "status": llm_evaluation_diagnostics["status"],
                "endpoint_configured": llm_evaluation_diagnostics["llm_endpoint"]["configured"],
                "live_status": llm_evaluation_diagnostics["live_llm_generation"]["status"],
                "diff_case_total": llm_evaluation_diagnostics["failure_analysis"]["diff_case_total"],
                "llm_generation_failure_total": llm_evaluation_diagnostics["failure_analysis"][
                    "llm_generation_failure_total"
                ],
                "next_command_total": len(llm_evaluation_diagnostics["next_commands"]),
            },
            "result_explanation_samples": {
                "allowed_validation_allowed": result_explanation_samples["allowed_sample"]["validation_allowed"],
                "blocked_validation_allowed": result_explanation_samples["blocked_sample"]["validation_allowed"],
                "coverage_total": len(result_explanation_samples["coverage_checks"]),
                "coverage_passed": sum(
                    1
                    for passed in result_explanation_samples["coverage_checks"].values()
                    if passed
                ),
            },
            "ui_layout_contract": {
                "passed": ui_layout_contract["passed"],
                "checked_files": ui_layout_contract["checked_files"],
                "contracts_total": len(ui_layout_contract["contracts"]),
                "contracts_passed": sum(
                    1
                    for contract in ui_layout_contract["contracts"].values()
                    if contract["passed"]
                ),
                "missing_files": ui_layout_contract["missing_files"],
            },
            "prd_thresholds": prd_thresholds,
            "evaluation_diff_summary": {
                "diff_case_total": evaluation_diff_summary["diff_case_total"],
                "failed_total": evaluation_diff_summary["failed_total"],
                "gold_mismatched_total": evaluation_diff_summary["gold_mismatched_total"],
                "llm_generation_failure_total": evaluation_diff_summary["llm_generation_failure_total"],
                "first_mismatch_total": evaluation_diff_summary["first_mismatch_total"],
            },
            "evaluation_total_cases": evaluation_summary["total_cases"],
            "evaluation_passed_cases": evaluation_summary["passed_cases"],
            "blocked_rejection_rate": evaluation_summary["blocked_rejection_rate"],
            "verified_total": verified_manifest["verified_total"],
            "catalog_issue_count": catalog_governance["issueCount"],
        },
        "files": files,
    }
    write_json(output_dir / files["manifest"], manifest)
    (output_dir / files["index"]).write_text(build_index_markdown(manifest), encoding="utf-8")
    return manifest


def main() -> None:
    args = parse_args()
    manifest = build_evidence_pack(args)
    print(f"Evidence pack: {args.output_dir}")
    print(f"Readiness required failures: {manifest['summary']['readiness_required_failed']}")
    print(f"Evaluation: {manifest['summary']['evaluation_passed_cases']}/{manifest['summary']['evaluation_total_cases']} passed")
    print(f"Evidence gate: {manifest['summary']['evidence_gate']['status']}")
    if args.strict and not manifest["summary"]["evidence_gate"]["passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
